Create func 15
hayrapetyanani/problems pull request #35
Opened 2021-07-12 20:38 UTC by ElyaHov

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +float funca( vector <int> & a, int n)
`n` ավելորդա որպես պարամետր։ Դրա փոխարեն ֆունկցիայի մեջ կարող ես գրել `a.size()`․․

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +        return (k);
փակագիծը ավելորդ է - պարզապես `return k;`

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    for(i=0;i<n;i++)
լավ կլիներ որ վերջից սկսեիր զանգվածի ու հենց առաջյին 0-ն տեսնեիր վերադարձնեիր։ Մեծ Օ-ի տեսակետից տարբերություն չկա բայց պրակտիկայում դա ավելի քիչ կամ հավասար քայլ կանի միշտ

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +int funcd (vector <int> & a, int n)
բոլոր այս ֆունկցիաներում դու վեկտորը չես փոխում այլ միայն կարդում ես նրա միջի էլէմենտները։ Հղում օգտագործելը լավ միտք է ավելորդ պատճենելուց խուսափելու համար բայց կարող ես նաև ավելացնել `const`: Կդառնա `const vector<int>& a`: Այդպես դու հստակ էս դարձնում բոլորի համար որ քո ֆունկցիան չի փոխելու իրեն փոխանցված արգումենտը

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    for(i=1;i<n;i++)
Միշտ լավ գաղափարա ցանկացած փոփոխականի սկոպը {scope) կամ տեսանելիության տիրույթը փոքր պահել։ Օրինակ `i` փոփոխականը չի օգտագործվում ցիկլից դուրս ուրեմն կարելի է այնպես անել որ դա տեսանելի մնա միայն ցիկլի մեջ։ Դրա համար պետք է գրել 
`for (**int** i = 1; i < n; i++)`

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    int i,k=0;
կարճ ֆունկցիաներում մեկ տառանի փոփոխականը խնդիր չի բայց որպես լավ ոճ դրեք իմաստալից անուններ։ Ձեր կոդը դուք գրում եք մեկ անգամ իսկ մյուսները կարդում են 100000 անգամ ու նույնիսկ 25 տարի հետո։ Ավելի ընթեռնելի լինելու համար օգտագործեք իմաստալից բայց ոչ շատ երկար անուններ։ Օրինակ `int k = 0` -> `int count = 0`:

Հետաքրքիր փաստ - Ծրագրավորողների մեջ ընդունված տերմինա ցեղային գիտելիք - դա երբ մեկը կամ մի քանիսը գիտեն ու հասկանում են ինչու է ծրագիրը տվյալ կետում անում ինչ որ քայլ բայց մյուս ոչ ցեղակիցները չգիտեն․ https://en.wikipedia.org/wiki/Tribal_knowledge
Լավ անուններ դնելով դուք խուսափում եք ցեղային գիտելիք ստեղծելուց եթե ի սկզբանե ձեր նպատակը դա չէր

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    s.resize(100);
զամբյուղներիդ քանակը պարզապես 100 վերցնելը կարող է ճիշտ չլինել։ Պատկերացրու `a`-ի մեջ կա 2 թիվ - մեկը 5 իսկ մյուսը 10000000։ Իսկ ինչպես լուծել այս խնդիրը՞

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    vector <int> s;
գովելի ա որ զամբյուղների մեթոդնես օգտագործել

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    max=s[a[0]-min];v=a[0];
քանի որ մենք գործ ունենք քանակների հետ որոնք դրական թվեր են մենք հանգիստ կարող ենք սկսել 0-ից (`max = 0`)

2021-07-12 22:02 UTC, paruyrkh commented on ElyaHovhannisyan/func 15
> +    float sum=0;
շատ լավա որ փոփոխականի անունը հուշում ա իրա իմաստի մասին

2021-07-12 22:04 UTC, paruyrkh commented
@ElyaHov կարող ես փորձել շտկումներ անել ու այս ֆայլի նոր տարբերակը ներբեռնել այնպես որ ես կարողանամ 2 օրինակն էլ տեսնեմ ու համեմատել թե ինչա փոխվել նախորդի հետ համեմատ՞ Էրիկը գիտի ձևը այնպես որ կարող ես հարցնել եթե հեշտ չգտնես ձևը

2021-07-12 22:05 UTC, paruyrkh requested changes
@ElyaHov Խնդրում եմ փորձիր շտկել ըստ նշվածների

2021-07-15 10:19 UTC, hayrapetyanani approved these changes
I am merging this file. But Paruyr's comments are very useful, please go over them when you find time.

2021-07-15 10:19 UTC, merged